### ISSUE TITLE
pip install python-snappy fails

### ISSUE THREAD

**Issue by obeleh** [andrix/python-snappy#20]
It failed for a first time so I figured I should first try to upgrade pip and then try again.

```
pip install --upgrade pip 
pip install python-snappy
```

I get the following output:

```
------------------------------------------------------------
C:\Python27\Scripts\pip-script.py run on 01/31/14 11:13:45
Downloading/unpacking python-snappy
  Getting page https://pypi.python.org/simple/python-snappy/
  URLs to search for versions for python-snappy:
  * https://pypi.python.org/simple/python-snappy/
  Analyzing links from page https://pypi.python.org/simple/python-snappy/
    Found link https://pypi.python.org/packages/source/p/python-snappy/python-snappy-0.2.1.tar.gz#md5=c34c46eb4c3f3673b1d3e85652edddd8 (from https://pypi.python.org/simple/python-snappy/), version: 0.2.1
    Found link https://pypi.python.org/packages/source/p/python-snappy/python-snappy-0.2.2.tar.gz#md5=8ea73ee4df62fa73d6a41a4a715f5df9 (from https://pypi.python.org/simple/python-snappy/), version: 0.2.2
    Found link https://pypi.python.org/packages/source/p/python-snappy/python-snappy-0.2.tar.gz#md5=6c86e44cc1bf4077cf4c7e70f1da2744 (from https://pypi.python.org/simple/python-snappy/), version: 0.2
    Found link https://pypi.python.org/packages/source/p/python-snappy/python-snappy-0.3.1.tar.gz#md5=872da91e53b63fb51e766cf3e67bc4fc (from https://pypi.python.org/simple/python-snappy/), version: 0.3.1
    Found link https://pypi.python.org/packages/source/p/python-snappy/python-snappy-0.3.2.tar.gz#md5=94ec3eb54a780fac3b15a6c141af973f (from https://pypi.python.org/simple/python-snappy/), version: 0.3.2
    Found link https://pypi.python.org/packages/source/p/python-snappy/python-snappy-0.3.tar.gz#md5=e3cac7f7872a3cdc2e719978626c96f0 (from https://pypi.python.org/simple/python-snappy/), version: 0.3
    Found link https://pypi.python.org/packages/source/p/python-snappy/python-snappy-0.4.tar.gz#md5=3e82ec29ddf47e63cb0c56ba48ea516c (from https://pypi.python.org/simple/python-snappy/), version: 0.4
    Found link https://pypi.python.org/packages/source/p/python-snappy/python-snappy-0.5.tar.gz#md5=044fb0ac21888c0b4eee0c4f15e75504 (from https://pypi.python.org/simple/python-snappy/), version: 0.5
    Skipping link http://code.google.com/p/snappy (from https://pypi.python.org/simple/python-snappy/); not a file
  Using version 0.5 (newest of versions: 0.5, 0.4, 0.3.2, 0.3.1, 0.3, 0.2.2, 0.2.1, 0.2)
  Downloading python-snappy-0.5.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/p/python-snappy/python-snappy-0.5.tar.gz#md5=044fb0ac21888c0b4eee0c4f15e75504 (from https://pypi.python.org/simple/python-snappy/)
  Running setup.py (path:c:\users\sjuul\appdata\local\temp\pip_build_sjuul\python-snappy\setup.py) egg_info for package python-snappy
    running egg_info
    creating pip-egg-info\python_snappy.egg-info
    writing pip-egg-info\python_snappy.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\python_snappy.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\python_snappy.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\python_snappy.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info\python_snappy.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info\python_snappy.egg-info\SOURCES.txt'
  Source in c:\users\sjuul\appdata\local\temp\pip_build_sjuul\python-snappy has version 0.5, which satisfies requirement python-snappy
Installing collected packages: python-snappy
  Running setup.py install for python-snappy
    Running command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\sjuul\\appdata\\local\\temp\\pip_build_sjuul\\python-snappy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\sjuul\appdata\local\temp\pip-ijfbau-record\install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    copying snappy.py -> build\lib.win32-2.7
    running build_ext
    building '_snappy' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tpsnappymodule.cc /Fobuild\temp.win32-2.7\Release\snappymodule.obj
    snappymodule.cc
    snappymodule.cc(31) : fatal error C1083: Cannot open include file: 'snappy-c.h': No such file or directory
    error: command '"c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe"' failed with exit status 2
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\sjuul\\appdata\\local\\temp\\pip_build_sjuul\\python-snappy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\sjuul\appdata\local\temp\pip-ijfbau-record\install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build\lib.win32-2.7

copying snappy.py -> build\lib.win32-2.7

running build_ext

building '_snappy' extension

creating build\temp.win32-2.7

creating build\temp.win32-2.7\Release

c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tpsnappymodule.cc /Fobuild\temp.win32-2.7\Release\snappymodule.obj

snappymodule.cc

snappymodule.cc(31) : fatal error C1083: Cannot open include file: 'snappy-c.h': No such file or directory

error: command '"c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe"' failed with exit status 2

----------------------------------------
Cleaning up...
  Removing temporary dir c:\users\sjuul\appdata\local\temp\pip_build_sjuul...
Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\sjuul\\appdata\\local\\temp\\pip_build_sjuul\\python-snappy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\sjuul\appdata\local\temp\pip-ijfbau-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\sjuul\appdata\local\temp\pip_build_sjuul\python-snappy
Exception information:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 279, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "c:\python27\lib\site-packages\pip\req.py", line 1380, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "c:\python27\lib\site-packages\pip\req.py", line 699, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "c:\python27\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\sjuul\\appdata\\local\\temp\\pip_build_sjuul\\python-snappy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\sjuul\appdata\local\temp\pip-ijfbau-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\sjuul\appdata\local\temp\pip_build_sjuul\python-snappy
```

**Comment by nitinzefr** [comment]
$ brew install snappy
$ pip install python-snappy

**Comment by jdelafon** [comment]
I still get the same error with snappy installed:

$ brew install snappy
Warning: snappy-1.1.3 already installed

$ pip2.7 --no-cache-dir install python-snappy
Collecting python-snappy
  Downloading python-snappy-0.5.tar.gz
Installing collected packages: python-snappy
  Running setup.py install for python-snappy ... error
    Complete output from command /Users/jdelafon/.virtualenvs/vcf2db/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/l_/1zwcrwvj3v7ck1zk6czkg8q40000gp/T/pip-build-SNmVOe/python-snappy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/l_/1zwcrwvj3v7ck1zk6czkg8q40000gp/T/pip-eKtKsK-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jdelafon/.virtualenvs/vcf2db/include/site/python2.7/python-snappy:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-intel-2.7
    copying snappy.py -> build/lib.macosx-10.11-intel-2.7
    running build_ext
    building '_snappy' extension
    creating build/temp.macosx-10.11-intel-2.7
    cc -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -I /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include -Qunused-arguments -Wno-unused-function -Wno-unused-variable -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c snappymodule.cc -o build/temp.macosx-10.11-intel-2.7/snappymodule.o
    snappymodule.cc:31:10: fatal error: 'snappy-c.h' file not found
    #include <snappy-c.h>
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/Users/jdelafon/.virtualenvs/vcf2db/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/l_/1zwcrwvj3v7ck1zk6czkg8q40000gp/T/pip-build-SNmVOe/python-snappy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/l_/1zwcrwvj3v7ck1zk6czkg8q40000gp/T/pip-eKtKsK-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jdelafon/.virtualenvs/vcf2db/include/site/python2.7/python-snappy" failed with error code 1 in /private/var/folders/l_/1zwcrwvj3v7ck1zk6czkg8q40000gp/T/pip-build-SNmVOe/python-snappy/
