### ISSUE TITLE
import error on python3.5 -- spherogram/no module named ordered_set

### ISSUE THREAD

**Issue by john-min** [andrix/python-snappy#47]
Using Anaconda here, but it also didn't work when not in the anaconda environment.

>>> import snappy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johnmin/src/anaconda3/lib/python3.5/site-packages/snappy/__init__.py", line 10, in <module>
    from .SnapPy import (AbelianGroup, HolonomyGroup, FundamentalGroup,
  File "SnapPycore.pxi", line 38, in init SnapPy (cython/SnapPy.c:104679)
  File "/Users/johnmin/src/anaconda3/lib/python3.5/site-packages/spherogram/__init__.py", line 3, in <module>
    from .links import *
  File "/Users/johnmin/src/anaconda3/lib/python3.5/site-packages/spherogram/links/__init__.py", line 1, in <module>
    from .links import Crossing, Strand, Link
  File "/Users/johnmin/src/anaconda3/lib/python3.5/site-packages/spherogram/links/links.py", line 1, in <module>
    from .links_base import Crossing, Strand, CrossingStrand, CrossingEntryPoint
  File "/Users/johnmin/src/anaconda3/lib/python3.5/site-packages/spherogram/links/links_base.py", line 12, in <module>
    from ordered_set import OrderedSet
ImportError: No module named 'ordered_set'

**Comment by martindurant** [comment]
The traceback suggests the existence of something called SnapPy which appears to have the same package name but actually refer to something completely different. I don't know what this may be, I haven't come across it before.

**Comment by andrix** [comment]
@john-min still having this issue? It seems it's not related to this library actually. I'll close it as it seems invalid.
