### ISSUE TITLE
Can't "import snappy" on Ubuntu 16.04 and Ubuntu 17.04

### ISSUE THREAD

**Issue by crossz** [andrix/python-snappy#50]
After having installed 1) snappy from github.com/google/snappy , and 2) sudo pip install python-snappy, in python 2.7 environment, I can not "import snappy". It threw errors like this:

```
>>> import snappy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/snappy.py", line 50, in <module>
    from snappy_cffi import UncompressError, compress, decompress, \
  File "/usr/local/lib/python2.7/dist-packages/snappy_cffi.py", line 3, in <module>
    from cffi import FFI
ImportError: cannot import name FFI
```

Importing cffi, made even worse, with more errors. 

How to fix this issue?

**Comment by martindurant** [comment]
Can you try after installing cffi?

**Comment by crossz** [comment]
even worse as mentioned, threw more errors about crc32c.c and crc32c.h.

**Comment by crossz** [comment]
I did all of these again at home, the errors after manual installation of cffi are like these:

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import snappy
/usr/local/lib/python2.7/dist-packages/__pycache__/_cffi__x762f05ffx6bf5342b.c: In function ‘_crc32c’:
/usr/local/lib/python2.7/dist-packages/__pycache__/_cffi__x762f05ffx6bf5342b.c:324:48: warning: pointer targets in passing argument 2 of ‘crc_update’ differ in signedness [-Wpointer-sign]
     return crc_finalize(crc_update(crc_init(), input, input_size));
                                                ^
/usr/local/lib/python2.7/dist-packages/__pycache__/_cffi__x762f05ffx6bf5342b.c:310:7: note: expected ‘const unsigned char *’ but argument is of type ‘const char *’
 crc_t crc_update(crc_t crc, const unsigned char *data, size_t data_len)
       ^
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/snappy.py", line 50, in <module>
    from snappy_cffi import UncompressError, compress, decompress, \
  File "/usr/local/lib/python2.7/dist-packages/snappy_cffi.py", line 169, in <module>
    ''', libraries=["snappy"])
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 438, in verify
    lib = self.verifier.load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/verifier.py", line 115, in load_library
    return self._load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/verifier.py", line 226, in _load_library
    return self._vengine.load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/vengine_cpy.py", line 159, in load_library
    raise VerificationError(error)
cffi.error.VerificationError: importing '/usr/local/lib/python2.7/dist-packages/__pycache__/_cffi__x762f05ffx6bf5342b.x86_64-linux-gnu.so': libsnappy.so.1.1.4: cannot open shared object file: No such file or directory
```

**Comment by crossz** [comment]
figture it out.
Have to install python-snappy from apt or yum before 'pip install python-snappy' for the dependencies installation.

I also created a pull request for the README about the scripts to install it on Vagrant VMs.

**Comment by martindurant** [comment]
@crossz , did you ever figure out which libraries were causing the conflict? Most conda packages, certainly on conda-forge, are build against pretty old systems (centos...), so there are always possible clib ABI incompatibilities. Conda now provides a lot of the tool chain itself, so it may be possible to rely on that instead of your native packaging system.

**Comment by jderrien** [comment]
Installing `libsnappy1v5` (on Ubuntu 16.04) worked for me.
