### ISSUE TITLE
Traceback in cli usage

### ISSUE THREAD

**Issue by ondrejhlavacek** [andrix/python-snappy#67]
When running python-snappy in CLI, in case of an error the traceback is written to `stderr`, eg:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/snappy/__main__.py", line 89, in <module>
    cmdline_main()
  File "/usr/local/lib/python3.5/dist-packages/snappy/__main__.py", line 85, in cmdline_main
    method(args.infile, args.outfile, **additional_args)
  File "/usr/local/lib/python3.5/dist-packages/snappy/hadoop_snappy.py", line 207, in stream_decompress
    start_chunk=start_chunk
  File "/usr/local/lib/python3.5/dist-packages/snappy/snappy.py", line 323, in stream_decompress
    decompressor.flush()  # makes sure the stream ended well
  File "/usr/local/lib/python3.5/dist-packages/snappy/hadoop_snappy.py", line 181, in flush
    raise UncompressError("chunk truncated")
snappy.UncompressError: chunk truncated
``` 

Can the traceback be ommited? Only the error message is required.

**Comment by ondrejhlavacek** [comment]
I'm keen on pushing a PR with some guidance. I've got a couple working solutions ready and tested.

**Comment by martindurant** [comment]
Does the same decompression work within the python interpreter?

**Comment by martindurant** [comment]
Ah, OK. In that case, I would put try/except around https://github.com/andrix/python-snappy/blob/master/snappy/__main__.py#L89 and handle the error with the amount of logging that suits you, or is specified via further user verbosity parameters.

**Comment by ondrejhlavacek** [comment]
Ok, thanks! Will send a pull request tomorrow and we can discuss the implementation details there.
