### ISSUE TITLE
Creating AWS Lambda layer leads to ._snappy_cfi missing problem

### ISSUE THREAD

**Issue by stevesuh** [andrix/python-snappy#88]
@dgrahn I'm doing something very similar but I'm still getting the error: `No module named 'snappy._snappy_cffi'`.

```
export PKG_DIR="python/lib/python3.6/site-packages"
yum --assumeyes install snappy-devel
 mkdir -p ${PKG_DIR}
pip install -r requirements.txt -t ${PKG_DIR}
```

When I ssh into the docker I see this:
```
bash-4.2# echo $LD_LIBRARY_PATH
/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
bash-4.2# find . -name *snapp*.so
./root/revelation-services/modules/get_kcf_waveform_data/build_layer/python/lib/python3.6/site-packages/snappy/_snappy.cpython-36m-x86_64-linux-gnu.so
./usr/lib64/libsnappy.so
```

Only difference is that we are using python3.6 image.
```
 docker:
      - image: lambci/lambda:build-python3.6
```

_Originally posted by @stevesuh in https://github.com/andrix/python-snappy/issues/82#issuecomment-529716921_

**Comment by stevesuh** [comment]
[pip install related output.txt](https://github.com/andrix/python-snappy/files/3593105/pip.install.related.output.txt)
[zip file contents.txt](https://github.com/andrix/python-snappy/files/3593108/zip.file.contents.txt)

**Comment by stevesuh** [comment]
From the Cloudwatch logs after added traceback.
```
Traceback (most recent call last):
File "/opt/python/lib/python3.6/site-packages/snappy/snappy.py", line 48, in <module>
from ._snappy import UncompressError, compress, decompress, \
ImportError: libsnappy.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/task/get_kcf_waveform_data.py", line 11, in <module>
import snappy
File "/opt/python/lib/python3.6/site-packages/snappy/__init__.py", line 3, in <module>
from .snappy import (
File "/opt/python/lib/python3.6/site-packages/snappy/snappy.py", line 51, in <module>
from .snappy_cffi import UncompressError, compress, decompress, \
File "/opt/python/lib/python3.6/site-packages/snappy/snappy_cffi.py", line 3, in <module>
from ._snappy_cffi import ffi, lib
ModuleNotFoundError: No module named 'snappy._snappy_cffi'
/opt/python/lib/python3.6/site-packages/numba/npyufunc/parallel.py:296: UserWarning: Could not obtain multiprocessing lock due to OS level error: [Errno 38] Function not implemented
```

**Comment by stevesuh** [comment]
https://github.com/andrix/python-snappy/issues/52

That resolved my issue.
